# Indexado y seleccion


In [2]:
# Importamos la biblioteca
import numpy as np
np.__version__

'1.22.4'

In [3]:
# Creamos un arreglo
a1=np.arange(5,15)
print(a1)

[ 5  6  7  8  9 10 11 12 13 14]


* La sintaxis con numpy es similar a la de Python usaremos $[]$ para indicar índices.
* Veamos el valor contenido en el índice *5*.

In [4]:
n=a1[5]
print(n)

10


## Slicing
* Podemos hacer **slicing**, tenemos que indicar el indice de inicio : el indice final.
* Hay que notar que **el índice final no se incluye**.

In [5]:
sub1=a1[1:5]
print(sub1)

[6 7 8 9]


* Si no colocamos el índice de inicio automaticamente lo toma desde el índice 0.

In [6]:
sub2=a1[:5]
print(sub2)

[5 6 7 8 9]


* Si no colocamos el índice final, toma desde el índice de inicio hasta el final del arreglo.
* El índice de inicio y el último elemento si son tomados

In [7]:
sub3=a1[3:]
print(sub3)

[ 8  9 10 11 12 13 14]


* Podemos colocar un valor en un índice en particular haciendo una asignación.

In [8]:
a1[3]=50
print(a1)

[ 5  6  7 50  9 10 11 12 13 14]


### Broadcast, vista y copy
* Tambien podemos hacer lo que se conoce como broadcast, que nos permite colocar un valor en varios elementos a la vez.

In [9]:
a1[4:8]=80
print(a1)

[ 5  6  7 50 80 80 80 80 13 14]


* Algo en lo que tenemos que tener mucho cuidado consiste en que cuando tomamos por slicing una parte del arreglo, no es una copia de los valores, sino solamente una vista del arreglo en el slice que  nosotros tomamos.
* Cualquier cambio al slice se ve reflejado en el array original

In [10]:
sub4=a1[0:5]
print(a1)
print(sub4)
sub4[:]=100
print(sub4)
print(a1)

[ 5  6  7 50 80 80 80 80 13 14]
[ 5  6  7 50 80]
[100 100 100 100 100]
[100 100 100 100 100  80  80  80  13  14]


* Si lo que deseamos es realmente tener una copia y no una referencia, hay que usar `copy` directamente.

In [11]:
a1=np.arange(5,15)
print(a1)
c1=a1.copy()
print(c1)
c1[:]=100
print(c1)
print(a1)

[ 5  6  7  8  9 10 11 12 13 14]
[ 5  6  7  8  9 10 11 12 13 14]
[100 100 100 100 100 100 100 100 100 100]
[ 5  6  7  8  9 10 11 12 13 14]


* Ahora trabajaremos con los índices de matrices.

In [12]:
m1=np.array([[2,4,6],[3,9,12],[8,16,20]])
print(m1)

[[ 2  4  6]
 [ 3  9 12]
 [ 8 16 20]]


* Para acceder a un elemento podemos usar la sintaxis de doble $[][]$ indicando la fila y la columna del elemento.

In [13]:
n2=m1[0][0]
print(n2)
n3=m1[2][1]
print(n3)

2
16


* **Existe otra notación que es muy utilizada en la que solo usamos un [] y las coordenadas se separan por comas**

In [14]:
n2=m1[0, 0]
print(n2)
n3=m1[2, 1]
print(n3)

2
16


### Extraccion filas y columnas
* Es posible tomar secciones de la matriz
* Podemos obtener una fila si solo indicamos un valor de indice

In [15]:
f1=m1[0]
print(f1)

[2 4 6]


In [16]:
# Ejercicio
m1[1]

array([ 3,  9, 12])

* Ahora tomaremos una submatriz, para esto necesitamos usar slicing.
* Tomaremos la submatriz superior derecha.
* Indicamos que deseamos en las filas desde el inicio hasta el indice 2(no se incluye) y para las columnas desde la 1 hasta el final

In [17]:
s1=m1[:2, 1:]
print(s1)

[[ 4  6]
 [ 9 12]]


* Si lo deseamos podemos obtener una columna, pero los valores van a ser colocados como array 1D, es decir como una fila.
* Podemos usar `reshape` si es necesario.

In [18]:
s2=m1[:,1]
print(s2)
s3=s2.reshape(-1,1)
print(s3)

[ 4  9 16]
[[ 4]
 [ 9]
 [16]]


### Seleccion condicional
* Tenemos lo que conocemos como seleccion condicional.
* Podemos llevar a cabo la comparación del array contra un valor y lo que obtenemos es un arreglo de booleanos donde nos dice que elementos cumplen o no la comparación.

In [19]:
print(a1)
c1= a1>10
print(c1)
c2= a1%2==0
print(c2)

[ 5  6  7  8  9 10 11 12 13 14]
[False False False False False False  True  True  True  True]
[False  True False  True False  True False  True False  True]


* Ahora solo tomaremos los valores donde el array es **True**.

In [20]:
v1=a1[c1]
print(v1)
v2=a1[c2]
print(v2)

[11 12 13 14]
[ 6  8 10 12 14]


* **Podemos llevar a cabo todo esto en una sola línea**

In [21]:
print(a1)
v3=a1[a1%2==0]
print(v3)

[ 5  6  7  8  9 10 11 12 13 14]
[ 6  8 10 12 14]


In [23]:
# ejercicio
print(a1)
v4 = a1[a1>8]
print(v4)

[ 5  6  7  8  9 10 11 12 13 14]
[ 9 10 11 12 13 14]
