# Operaciones con arreglos en NumPy

In [1]:
import numpy as np
np.__version__

'1.22.4'

In [2]:
a1 = np.arange(0,11)
print(a1)
a2= np.arange(20,31)
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[20 21 22 23 24 25 26 27 28 29 30]


## Operaciones aritmeticas
* La adición, resta, división y producto por elementos

In [4]:
a3=a1+a2
print(a3)
a4=a1-a2
print(a4)
a5=a1/a2
print(a5)

[20 22 24 26 28 30 32 34 36 38 40]
[-20 -20 -20 -20 -20 -20 -20 -20 -20 -20 -20]
[0.         0.04761905 0.09090909 0.13043478 0.16666667 0.2
 0.23076923 0.25925926 0.28571429 0.31034483 0.33333333]


* Se pueden hacer operaciones con escalares, el escalar va a hacer un **broadcast** a los elementos del array.

In [6]:
a6= a1+50
print(a6)
a7= a1-10
print(a7)
a8=a1*3
print(a8)
a9=a1**3
print(a9)

[50 51 52 53 54 55 56 57 58 59 60]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0]
[ 0  3  6  9 12 15 18 21 24 27 30]
[   0    1    8   27   64  125  216  343  512  729 1000]


## Funciones universales
* Funciones universales de arreglos, son operaciones matemáticas que hacen **broadcast** al arreglo completo**
  * sqrt ->$\sqrt{}$: raiz cuadrada.
  * exp ->$e^x$
  * `max` encuentra el máximo.
  * $\sin$, $\cos$, etc funciones trigonometricas, en radianes.
  * $log$ logaritmo natural. $Log(0) = -inf$, obtenemos un warning.
* https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [7]:
a10=np.sqrt(a1)
print(a10)
a11=np.exp(a1)
print(a11)
maximo=np.max(a1)
print(maximo)
a12=np.sin(a1)
print(a12)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
10
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]


In [8]:
# Al usar log tenemos que tener cuidado con valores que sean 0
a13=np.log(a2)
print(a13)

[2.99573227 3.04452244 3.09104245 3.13549422 3.17805383 3.21887582
 3.25809654 3.29583687 3.33220451 3.36729583 3.40119738]


* Podemos obtener la sumatoria de los elementos del arrgo

In [9]:
sumatoria=a1.sum()
print(sumatoria)

55


* Ahora la desviacion estandard

In [10]:
desv=a1.std()
print(desv)

3.1622776601683795


## Opeaciones con filas y columnas
* Ahora podemos obtener la suma de filas o columnas de una matriz

In [11]:
m1=np.arange(1,26).reshape(5,5)
print(m1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [12]:
# axis=0 -> suma de columnas
# axis=1 -> suma de filas
sumCol=m1.sum(axis=0)
print(sumCol)

[55 60 65 70 75]


In [13]:
sumFila=m1.sum(axis=1)
print(sumFila)

[ 15  40  65  90 115]


# Concatenacion de arrays
* Los arrays se pueden concatenar, pero debemos de **tener cuidado con las dimensiones para que se pueda llevar a cabo**.
* Se puede concatenar mas de dos arreglos a la vez

In [14]:
print(a1,a1.shape)
print(a2,a2.shape)
concatenado=np.concatenate([a1,a2])
print(concatenado,concatenado.shape)

[ 0  1  2  3  4  5  6  7  8  9 10] (11,)
[20 21 22 23 24 25 26 27 28 29 30] (11,)
[ 0  1  2  3  4  5  6  7  8  9 10 20 21 22 23 24 25 26 27 28 29 30] (22,)


In [15]:
ma1=np.array([[1,2,3],[4,5,6]])
ma2=np.array([[11,12,13],[14,15,16]])
print(ma1,ma1.shape)
print(ma2,ma2.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[11 12 13]
 [14 15 16]] (2, 3)


In [18]:
# Concatenamos en el eje 0
mc0=np.concatenate([ma1,ma2], axis=0)
print(mc0)
print(mc0.shape)

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]
(4, 3)


In [19]:
# Concatenamos en el eje 1
mc1=np.concatenate([ma1,ma2], axis=1)
print(mc1)
print(mc1.shape)

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]
(2, 6)


In [21]:
ma3=np.array([[21,22],[31,32]])
print(ma3,ma3.shape)

# Un error se produce cuando las dimensiones no coinciden. ma1 tiene 3 columnas, ma3 tiene 2 columnas
mc=np.concatenate([ma1,ma3], axis=0)

[[21 22]
 [31 32]] (2, 2)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

# Split
* Se puede separar el array en varios subarrays.
* Hay que tener cuidado que se pueda dividir la cantidad de columnas/filas de forma exacta entre el número de divisiones que deseamos

In [22]:
a1=np.arange(12)
print(a1)

# Indicamos el array a dividir y el numero de divisiones
divisiones= np.split(a1,3)
print(divisiones)
print('------')
divisiones= np.split(a1,4)
print(divisiones)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
------
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


In [23]:
# Veamos que ocurre si no hay division exacta
divisiones= np.split(a1,5)
print(divisiones)

ValueError: array split does not result in an equal division

In [24]:
# Podemos indicar los indices donde deseamos las divisiones
# Pasamos una lista con los indices donde deseamos el corte
divisiones=np.split(a1,[2,7])
print(divisiones)

[array([0, 1]), array([2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11])]


In [25]:
# Si deseamos hacer divisiones aunque no tengan la misma cantidad de elementos
# usamos array_split en lugar de split
divisiones= np.array_split(a1,5)
print(divisiones)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9]), array([10, 11])]


Los splits anteriores funcionan de manera horizontal, pero tambien hay funciones para dividir arrays de forma vertical

In [26]:
a3=np.arange(24).reshape(-1,4)
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [27]:
# vsplit() nos permite dividir a partir de las filas
dividido=np.vsplit(a3,3)
print(dividido)
print('------')
for n in dividido:
  print(n)
  print('------')

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]
------
[[0 1 2 3]
 [4 5 6 7]]
------
[[ 8  9 10 11]
 [12 13 14 15]]
------
[[16 17 18 19]
 [20 21 22 23]]
------


In [28]:
# hsplit() nos permite dividir a partir de las columnas
dividido=np.hsplit(a3,2)
print(dividido)
print('------')
for n in dividido:
  print(n)
  print('------')

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])]
------
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]]
------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]]
------
